databases:
  - name: yuya_DB
    databaseName: yuya_db
    user: yuya_DB
    region: singapore

services:
  - type: web
    name: yuya
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: yuya_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

